window.TRIP={
  "places": [
    {
      "id": "kkudeok",
      "name": "을왕리 꾸덕집 영종본점",
      "type": "food",
      "zone": "west",
      "region": "을왕리·용유",
      "kind": "생선구이·솥밥 정식",
      "menu": "모듬 생선구이 정식 19,000원 · 장어강정 포함 원조 정식 21,000원 · 직화 제육 정식 18,000원",
      "why": "생선구이와 밥·반찬을 든든하게 먹고 싶을 때 고르기 좋은 한식 후보. 조개구이와 다른 메뉴로 비교하기 좋아요.",
      "caution": "용유서로174번길 44. 09:30~20:00, 라스트오더 19:00 안내. 첫날 자전거를 19시에 마치면 늦으므로 점심 또는 이른 저녁 후보로 추천해요.",
      "review": "다이닝코드 4.1/5 · 48명",
      "reviewNote": "푸짐한 생선·반찬 구성 호평. 맛 만족도 차이와 주말 대기·주차장 진입 혼잡 후기도 있어요.",
      "when": "첫날 점심 또는 둘째 날 이른 저녁 후보",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260331080930361_photo_2c26a0789a0a.webp",
      "source": "https://www.diningcode.com/profile.php?rid=yNXieG4swdb1",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "parkingTitle": "무료 주차 · 주말 혼잡 주의",
      "parking": "무료 주차 안내·후기 확인. 주말에는 주차장 진입부터 대기했다는 후기도 있어 빈자리·빠른 주차는 보장하기 어려워요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=yNXieG4swdb1",
      "info": "https://polle.com/place/2dLZMg/",
      "evidence": "2026.10.08 다이닝코드 매장 정보 및 뽈레 후기 확인. 가격·영업시간은 변동 가능하며 방문 전 네이버지도 최신 공지를 확인하세요."
    },
    {
      "id": "joeun",
      "name": "조은전골칼국수",
      "type": "food",
      "zone": "central",
      "region": "운남동",
      "kind": "칼국수·보쌈",
      "menu": "칼국수+맛보쌈 11,000원 · 무한리필 칼국수+보쌈 14,000원",
      "why": "칼국수와 보쌈을 한 끼로 먹기 좋은 마지막 날 점심 우선 후보. 짧은 영업시간을 고려해 산책보다 먼저 가요.",
      "caution": "운중로 84. 일요일 10:30~15:00 안내, 금요일 정기휴무. 대기·조기 마감 가능성 고려. 예약·방문 확정 아님.",
      "review": "다이닝코드 4.8/5 · 26명",
      "reviewNote": "진한 국물·보쌈·양에 호평. 대기와 협소한 주차 후기도 확인했어요.",
      "when": "마지막 날 · 11시 체크아웃 후 점심 우선 후보",
      "source": "https://www.diningcode.com/profile.php?rid=CU57HsXehwV2",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20261003025358_photo1_8f9a4e6661c6.webp",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "parkingTitle": "주차 안내",
      "parking": "매장 앞 무료 주차 공간이 작아 혼잡 후기가 있어요. 만차 시 인근 유료 주차 위치를 현장에서 확인해야 하므로 주차 우선 후보에서는 제외.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=CU57HsXehwV2",
      "price": null,
      "evidence": "2026.10.08 공개 매장 안내·노출 후기 확인. 추천 이유와 방문 순서는 편집 제안이며, 가격·영업시간·주차 정책은 현장 변경 가능."
    },
    {
      "id": "aloha",
      "name": "알로하보일링크랩 을왕본점",
      "type": "food",
      "zone": "west",
      "region": "왕산·을왕리",
      "kind": "미국식 해물찜·랍스터",
      "menu": "보일링씨푸드 2인 70,000원 · 랍스터 추가 구성 별도",
      "why": "소스를 버무린 해산물을 함께 먹는 이색 메뉴. 왕산해변 방문 후 저녁으로 비교하기 좋아요.",
      "caution": "용유서로423번길 7-1. 영업 종료·휴무 안내가 출처마다 달라 방문 전 0507-1321-7299 확인.",
      "review": "네이버 검색 표시 별점 4.95 · 리뷰 1,282",
      "reviewNote": "2026.10.08 검색 매장 카드 표시값. 리뷰 수를 방문자 평가 수로 단정하지 않았어요. 오션뷰·소스 호평과 가격 부담 후기가 함께 있어요.",
      "when": "첫날 또는 둘째 날 · 왕산 노을 후 저녁",
      "source": "https://www.diningcode.com/profile.php?rid=5CsbJqlqc3q7",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260330032036_photo1_7afb57c4dfa8.webp",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "parkingTitle": "주차 안내",
      "parking": "전용·제휴 주차 후기 있음. 매장 앞 청춘조개 주차장 3시간 무료 후기가 있으나 지정 구역·현재 조건 확인 필요.",
      "parkingPreferred": false,
      "parkingSource": "https://blog.naver.com/jeeee_419/224419017270",
      "price": null,
      "evidence": "2026.10.08 공개 매장 안내·노출 후기 확인. 추천 이유와 방문 순서는 편집 제안이며, 가격·영업시간·주차 정책은 현장 변경 가능.",
      "query": "알로하보일링크랩 을왕본점"
    },
    {
      "id": "siru",
      "name": "시루앤케이크",
      "type": "cafe",
      "zone": "west",
      "region": "공항서로·남북동",
      "kind": "떡케이크·베이커리",
      "menu": "흑임자 등 설기케이크 · 소금빵 · 커피 · 상하목장 아이스크림",
      "why": "떡 디저트를 고를 수 있고 넓은 실내·주차장이 장점인 후보. 바다 대신 전원 풍경과 비행기 구경을 원할 때 좋아요.",
      "caution": "공항서로 459. 10/9~11은 10:30~20:00 안내, 주말 라스트오더 19:45. 동물·좌석 운영과 당일 디저트 재고는 변동 가능.",
      "review": "다이닝코드 4.4/5 · 10명",
      "reviewNote": "주차·떡 디저트 호평. 맛·가격 만족도는 후기별 차이가 있어요.",
      "when": "첫날 입도 후 또는 둘째 날 리조트 외부 카페 선택",
      "source": "https://www.diningcode.com/profile.php?rid=i9P4jCOcefg3",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260530044557_photo1_638cfd8288c3.webp",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "parkingTitle": "주차 안내",
      "parking": "전용 무료 주차장과 넓은 주차 공간 후기가 반복 확인돼 주차 우선 후보로 넣었어요. 연휴 빈자리는 보장되지 않아요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=i9P4jCOcefg3",
      "price": null,
      "evidence": "2026.10.08 공개 매장 안내·노출 후기 확인. 추천 이유와 방문 순서는 편집 제안이며, 가격·영업시간·주차 정책은 현장 변경 가능.",
      "info": "https://sirucake.com/shop_view/?idx=1"
    },
    {
      "id": "yedan",
      "name": "예단포 둘레길",
      "type": "walk",
      "zone": "central",
      "region": "예단포·운북",
      "kind": "가벼운 해안 산책",
      "menu": "선착장 → 미단시티 공원 해안 산책로 → 정자 → 원점 / 사진·휴식 포함 40~60분 제안",
      "why": "이번 일정에 잘 맞는 짧은 산책 후보. 소무의도보다 걷는 시간을 줄이고 점심·카페를 여유롭게 넣고 싶을 때 추천해요.",
      "caution": "공식 소개는 1km 남짓, 정자까지 약 15분. 코스 전체와 편도·왕복 표기가 다를 수 있어 총거리를 단정하지 않았어요. 일부 계단·흙길. 만조·간조에 따라 바다 대신 갯벌이 넓게 보여요.",
      "source": "https://itour.incheon.go.kr/thmtour/thmtour/detail.do?cotId=ITA25061617575280445",
      "image": "https://itour.incheon.go.kr/upload/image/2025/06/16/ae8edc59-feb4-460f-87a0-edfd46f29474.jpg",
      "credit": "인천투어 · 예단포",
      "parking": "선착장 무료 주차 공식 안내. 연휴 빈자리·진입 대기는 미확인.",
      "parkingTitle": "주차 안내",
      "parkingSource": "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=APD21120810001467186",
      "when": "마지막 날 · 소무의도 대신 선택",
      "query": "영종도 예단포 둘레길",
      "evidence": "공식 관광 안내 확인 2026.10.08. 휴식 포함 시간과 일정 추천은 편집 제안. 당일 통제는 미확인."
    },
    {
      "id": "baekryeon",
      "name": "백련산 숲길",
      "type": "walk",
      "zone": "central",
      "region": "운서",
      "kind": "짧은 산행 · 공식 쉬움",
      "menu": "공식 2km·50분 / 전망대·휴식 포함 1~1.5시간 제안",
      "why": "바다 대신 숲을 걷고 싶고 긴 산행은 부담스러울 때. 세계평화의숲과 연계할 수 있어요.",
      "caution": "남쪽은 완만하고 북쪽은 상대적으로 경사 있음. 표기 시간은 관광 안내 기준, 개인 체력에 따라 달라요.",
      "source": "https://www.yeongjong.go.kr/tour/content/view.do?sn=909",
      "image": "https://www.yeongjong.go.kr/main/images/culture/sub/forest_img05.png",
      "credit": "영종구청 · 백련산 전망대",
      "parking": "등산로 입구별 전용 주차 위치·무료 여부 미확인. 출발 지점과 주차를 먼저 정하세요.",
      "parkingTitle": "주차 안내",
      "parkingSource": "https://www.yeongjong.go.kr/tour/content/view.do?sn=909",
      "when": "마지막 날 · 소무의도 대신 선택",
      "query": "영종도 백련산 숲길",
      "evidence": "공식 관광 안내 확인 2026.10.08. 휴식 포함 시간과 일정 추천은 편집 제안. 당일 통제는 미확인."
    },
    {
      "id": "pim",
      "name": "핌 카페 PIM",
      "type": "cafe",
      "zone": "east",
      "region": "중산·하늘대교",
      "kind": "우드 인테리어 · 대교뷰",
      "menu": "스페셜티 핸드드립 · 바닐라빈라떼 · 소금빵·케이크",
      "why": "새우 식사 뒤 동쪽에서 카페까지 묶고 싶을 때. 원목 가구와 통창, 대교 전망을 보는 선택지예요.",
      "review": "다이닝코드 4.0/5 · 1명",
      "reviewNote": "평가가 1명뿐이라 평점 순위로 추천하지 않습니다. 공개 방문기에서 통창·원목 공간·베이커리 소개 확인.",
      "parking": "제1·2 주차장 후기. 건물 뒤 주차 규모가 작다는 설명도 있어 만차 시 매장에 지정 장소 문의.",
      "parkingTitle": "주차 가능 · 규모 유의",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=oa0f7ERxPyFC",
      "caution": "중산로87번길 40-43 · 평일·주말 마감 안내가 달라 방문일 운영시간 확인. 공도 임의 주차는 추천하지 않습니다.",
      "when": "첫날 입도·마지막 날 카페 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260906113924629_photo_52b681e9990a.webp",
      "source": "https://www.diningcode.com/profile.php?rid=oa0f7ERxPyFC",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "query": "영종도 핌 카페 PIM",
      "evidence": "2026.10.08 공개 매장정보·후기 확인. 네이버 별점은 미확인. 추천 조합은 동선·취향에 따른 편집 제안."
    },
    {
      "id": "pyeong",
      "name": "평상인제빵소",
      "type": "cafe",
      "zone": "east",
      "region": "구읍뱃터",
      "kind": "바다·대교뷰 · 베이커리",
      "menu": "크림라떼 · 소금빵 · 크루아상 · 베이커리",
      "why": "빵 고르는 재미와 바다 전망을 함께 원할 때. 식사 뒤 카페에 앉았다가 영종진광장 산책으로 연결하기 좋아요.",
      "review": "다이닝코드 4.3/5 · 15명",
      "reviewNote": "바다 전망·공간·빵 관련 후기. 창가 자리는 방문 시간에 따라 달라집니다.",
      "parking": "건물 지하 주차 안내. 인근 오션테라스 지원 후기는 최대 2시간으로, 현재 제휴·등록 조건 확인.",
      "parkingTitle": "주차 우선 후보",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=5zZwVBJEgfAN",
      "caution": "영종진광장로 46 · 인근 카페 평상인과 매장을 구분하세요. 공개 안내 10~22시, 변경 가능.",
      "when": "첫날 입도·마지막 날 카페 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20251104154716_photo1_3e93cfbdf363.webp",
      "source": "https://www.diningcode.com/profile.php?rid=5zZwVBJEgfAN",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "query": "영종도 평상인제빵소",
      "evidence": "2026.10.08 공개 매장정보·후기 확인. 네이버 별점은 미확인. 추천 조합은 동선·취향에 따른 편집 제안."
    },
    {
      "id": "starfive",
      "name": "스타파이브 카페",
      "type": "cafe",
      "zone": "central",
      "region": "공항·용유",
      "kind": "비행기뷰 · 베이커리",
      "menu": "메이플 크림라떼 · 아인슈패너 · 베이커리",
      "why": "바다 풍경과 다른 카페를 원하면 비행기 구경과 빵을 묶는 선택. 넓은 공간에서 쉬는 드라이브 코스로 추천해요.",
      "review": "다이닝코드 4.3/5 · 24명",
      "reviewNote": "공항 전망과 다양한 빵을 즐기는 후기. 비행기가 보이는 정도는 좌석·운항 상황에 따라 달라요.",
      "parking": "넓은 자체 주차장·무료 주차 안내와 후기. 연휴 혼잡은 별도 고려.",
      "parkingTitle": "주차 우선 후보",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=jbcb1Fku6vIX",
      "caution": "공항서로 133-1 · 비행기 근접 촬영 장소나 활주로 관람 시설은 아닙니다.",
      "when": "첫날 입도·마지막 날 카페 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260526072825771_photo_6eee89135ef7.webp",
      "source": "https://www.diningcode.com/profile.php?rid=jbcb1Fku6vIX",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "query": "영종도 스타파이브 카페",
      "evidence": "2026.10.08 공개 매장정보·후기 확인. 네이버 별점은 미확인. 추천 조합은 동선·취향에 따른 편집 제안."
    },
    {
      "id": "brasserie",
      "name": "브라세리 1783",
      "type": "cafe",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "베이커리·올데이 다이닝",
      "menu": "빵 / 프렌치 스타일 다이닝",
      "why": "카페와 가벼운 식사 사이에서 고르고 싶을 때. 열기구를 연상시키는 중앙 디자인을 보는 재미도 있어요.",
      "caution": "공식 주말 베이커리 08~22시. 다이닝 주문 시간·현재 메뉴는 별도 확인.",
      "review": "네이버 평점·리뷰 수 미확인",
      "reviewNote": "공식 공간·베이커리 소개 기반. 둘째 날 사진·휴식 후보.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_crop%2Cw_3450%2Ch_3098%2Cq_80%2Cf_auto%2Cx_577/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/GMPIK_Brasserie_1783.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 브라세리 1783",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 브라세리 1783",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "baker",
      "name": "베이커스 키친",
      "type": "cafe",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "빵·커피",
      "menu": "페이스트리 / 빵 / 커피",
      "why": "리조트 구경 사이에 빵과 커피로 짧게 쉬고 싶을 때. 긴 식사 일정을 추가하지 않는 선택.",
      "caution": "공식 매일 07~21시. 빵 종류·재고는 방문 시간에 따라 달라요.",
      "review": "네이버 평점·리뷰 수 미확인",
      "reviewNote": "공식 베이커리 소개 기반. 특정 빵의 맛 순위는 확인하지 않음.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_540%2Ch_485%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/0103_Baker_s_Kitchen__1_.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 베이커스 키친",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 베이커스 키친",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "horizon",
      "name": "호라이즌 라운지",
      "type": "cafe",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "로비 라운지",
      "menu": "커피 / 디저트 / 시그니처 음료",
      "why": "돌아다니다 앉아서 쉬는 시간이 중요하면 후보. 라운지 공간과 조명 분위기를 즐기는 선택.",
      "caution": "공식 매일 07~22시. 가격·좌석 상황·디저트 구성 확인.",
      "review": "네이버 평점·리뷰 수 미확인",
      "reviewNote": "공식 공간 소개 기반. 커피 맛보다 라운지 분위기를 기준으로 추천.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_540%2Ch_485%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/0104_Horizon_Lounge__2_.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 호라이즌 라운지",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 호라이즌 라운지",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "chadeok",
      "type": "cafe",
      "name": "차덕분 영종도본점",
      "query": "차덕분 영종도본점",
      "region": "구읍뱃터·동쪽",
      "kind": "전통차·다과",
      "when": "선택 · 첫날 점심 후 / 15시 체크인에 여유가 있을 때",
      "why": "바다를 보며 차와 작은 다과를 천천히 즐기는 선택. 빵·커피 중심 카페와 다른 분위기를 원하면 이곳을 먼저 골라요.",
      "menu": "잎차·꽃차·냉차 / 모나카·곶감말이 등 다과",
      "caution": "공식 안내상 주말·공휴일 09:30~21:00. 다과 구성·현재 가격은 현장 확인.",
      "image": "https://tong.visitkorea.or.kr/cms/resource/63/3487563_image2_1.jpg",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?menuSn=352&vcontsId=230916",
      "info": "https://www.thankstotea.com/lng",
      "credit": "한국관광공사 · 차덕분",
      "evidence": "한국관광공사 사진·소개 및 차덕분 공식 안내. 바다 전망 좌석 확보는 보장되지 않음.",
      "zone": "east",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "주차 가능 · 편의 미확인",
      "parking": "관광정보에 주차 가능으로 안내됩니다. 구읍뱃터 혼잡과 실제 주차 위치를 고려하세요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.ktriptips.com/kor/food/2812241"
    },
    {
      "id": "mieum",
      "type": "cafe",
      "name": "미음",
      "query": "영종도 미음 마시란로119",
      "region": "마시안·서쪽",
      "kind": "베이커리·오션뷰",
      "when": "추천 · 마지막 날 점심 후",
      "why": "서해와 갯벌을 보며 빵·커피를 즐길 수 있는 카페. 소무의도 산책을 마친 뒤 앉아서 쉬는 마지막 장소로 잘 맞아요.",
      "menu": "커피 / 미음 크림라떼 / 베이커리",
      "caution": "관광정보상 금·주말 10:00~21:00, 마지막 주문 20:30. 창가·바다 모습은 좌석과 물때에 따라 달라요.",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20251111124255_photo1_cd0ac61eb680.webp",
      "source": "https://www.diningcode.com/profile.php?rid=a4RWOj3EVTsa",
      "info": "https://www.ktourmap.com/spotDetails.jsp?contentId=3575577",
      "credit": "다이닝코드 · 미음",
      "evidence": "마시란로 119. 운영시간·대표 메뉴는 관광정보 확인. 베이커리 종류는 변동 가능.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "주차 우선 후보",
      "parking": "넓은 주차장 후기가 있어요. 무료 시간이 출처마다 달라 결제 시 차량 등록·이용 시간을 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=a4RWOj3EVTsa"
    },
    {
      "id": "made",
      "type": "cafe",
      "name": "메이드림",
      "query": "영종도 메이드림",
      "region": "을왕리·왕산 권역",
      "kind": "공간 구경·베이커리",
      "when": "선택 · 미음 대신 / 리조트 일정을 줄일 때",
      "why": "옛 교회를 개조한 숲 테마 공간과 스테인드글라스가 특징. 바다 전망보다 실내 사진과 건축 구경을 좋아하면 잘 맞아요.",
      "menu": "커피 / 베이커리·케이크 / 다이닝",
      "caution": "인스파이어와 함께 넣으면 실내 구경이 많아져요. 이번 일정에서는 추가보다 다른 카페와 교체 추천. 운영·가격 미확인.",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260518054613_photo1_4451f6b05a6e.webp",
      "source": "https://www.diningcode.com/profile.php?rid=PsNCvwWyhOSf",
      "info": "https://itour.incheon.go.kr/thmtour/thmtour/detail.do?cotId=ITA23062713332301098",
      "credit": "다이닝코드 · 메이드림",
      "evidence": "공간 특징은 인천관광 공식 소개, 메뉴·사진은 공개 매장 후기 확인.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "주차 우선 후보",
      "parking": "전용 주차장·여유 있는 규모 후기가 있어요. 차량번호 등록과 무료 시간은 결제 시 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=PsNCvwWyhOSf"
    },
    {
      "id": "cliff",
      "name": "엠클리프",
      "type": "cafe",
      "zone": "west",
      "region": "마시안·서쪽",
      "kind": "오션뷰·베이커리",
      "menu": "커피·라떼 / 베이커리",
      "why": "높은 자리에서 서해를 바라보는 카페를 원하면 우선 후보. 미음과 비교해 전망·공간 취향으로 고르면 좋아요.",
      "caution": "주말 혼잡·가격 부담 후기가 있음. 인스타 공개 게시물이 오래돼 운영시간은 최신 지도 확인 우선.",
      "review": "다이닝코드 4.1 / 5 · 57명",
      "reviewNote": "오션뷰·테라스 장점. 공개 후기에는 리뷰 작성 혜택 언급도 있어 평점만으로 선정하지 않았어요.",
      "when": "취향에 따라 기존 카페와 교체",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260705093438408_photo_2396b69de04a.webp",
      "source": "https://www.diningcode.com/profile.php?rid=FstRgb32Ib4D",
      "credit": "다이닝코드 · 엠클리프",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": "https://www.instagram.com/cafe_m_cliff/",
      "parkingTitle": "전용 주차 · 진입 혼잡",
      "parking": "주차장 이용 가능하나 좁은 진입로와 입출차 대기 후기가 있어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=FstRgb32Ib4D"
    },
    {
      "id": "billy",
      "name": "빌리앤오티스",
      "type": "cafe",
      "zone": "central",
      "region": "운북·북동쪽",
      "kind": "베이커리·정원",
      "menu": "커피 / 호지차 / 빵",
      "why": "바다 전망보다 빵과 정원, 높은 천장의 공간을 원할 때. 같은 오션뷰 카페만 반복하지 않는 대안이에요.",
      "caution": "서쪽 숙소와 동선이 달라 일부러 들르는 후보. 가족 손님·주말 혼잡을 고려하세요.",
      "review": "다이닝코드 4.2 / 5 · 31명",
      "reviewNote": "베이커리와 야외 좌석을 좋게 보는 후기. 조용한 대화보다 넓은 공간 구경에 무게를 두세요.",
      "when": "취향에 따라 기존 카페와 교체",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260914045533_photo1_6f3d5587c93f.webp",
      "source": "https://www.diningcode.com/profile.php?rid=TOnMtPIGVLfy",
      "credit": "다이닝코드 · 빌리앤오티스",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "주차 우선 후보",
      "parking": "맞은편 넓은 주차장·무료 주차 후기가 있어요. 건너편 주차 시 보행 이동을 고려하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=TOnMtPIGVLfy"
    },
    {
      "id": "masian",
      "name": "마시안제빵소",
      "type": "cafe",
      "zone": "west",
      "region": "마시안·서쪽",
      "kind": "해변·빵",
      "menu": "연탄식빵 / 커피 / 베이커리",
      "why": "해변 산책과 빵을 한 번에 즐기고 싶을 때. 시그니처 연탄식빵이 있어 디저트 목적이 분명한 후보.",
      "caution": "인기 빵 품절·주차·주문 대기 후기. 빵 나오는 시간은 당일 확인.",
      "review": "다이닝코드 3.8 / 5 · 48명",
      "reviewNote": "바다 전망·빵 선택 폭은 장점. 혼잡과 서비스 경험은 갈려 맛집 최우선보다 해변 결합 후보로 추천.",
      "when": "취향에 따라 기존 카페와 교체",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260824071843109_photo_2494cd79f4dd.webp",
      "source": "https://www.diningcode.com/profile.php?rid=bBnlAVuljYEN",
      "credit": "다이닝코드 · 마시안제빵소",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "전용·맞은편 주차장",
      "parking": "주차 공간은 있으나 주말 주차 대기 후기가 있어요. 영수증·무료 시간 확인.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=bBnlAVuljYEN"
    },
    {
      "id": "bada",
      "name": "바다앞테라스",
      "type": "cafe",
      "zone": "east",
      "region": "구읍뱃터·동쪽",
      "kind": "바다 전망·루프탑",
      "menu": "커피 / 과일 음료 / 베이커리",
      "why": "첫날 구읍뱃터 점심 뒤 가기 좋은 대표 후보. 차덕분의 차·다과 대신 빵과 바다 전망을 원할 때.",
      "caution": "인스타 프로필에서 은하수로 10의 4~5층 확인. 인기 시간대 조용한 좌석 확보는 어려울 수 있어요.",
      "review": "다이닝코드 4.0 / 5 · 50명",
      "reviewNote": "전망·사진에 대한 장점이 크고 커피 맛·가격 평가는 상대적으로 낮음. 분위기 우선으로 고르세요.",
      "when": "취향에 따라 기존 카페와 교체",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260601042757_photo1_c4a24d9f77bf.webp",
      "source": "https://www.diningcode.com/profile.php?rid=vR7q9oVXGs6n",
      "credit": "다이닝코드 · 바다앞테라스",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": "https://www.instagram.com/terrace.in.seaside/",
      "parkingTitle": "건물 지하 · 할인 확인",
      "parking": "지하 주차장 등록·할인 후기. 주변 야외 유료 주차장과 구분하세요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=vR7q9oVXGs6n"
    },
    {
      "id": "nakjo",
      "name": "낙조대 카페",
      "type": "cafe",
      "zone": "west",
      "region": "을왕리·서쪽",
      "kind": "전망·파르페",
      "menu": "커피 / 파르페 / 케이크",
      "why": "숙소 주변에서 바다 풍경을 크게 보고 싶을 때의 공간 후보. 맛 최우선보다는 전망을 즐기는 선택이에요.",
      "caution": "가격 부담·음료 맛에 아쉽다는 후기가 있어요. 조용한 커피 맛집으로는 우선순위를 낮췄습니다.",
      "review": "네이버 검색 리뷰 6,427 · 별점 미표시",
      "reviewNote": "다이닝코드 3.1/5·3명으로 표본은 작지만 음료에 불만 후기. 네이버 노출 후기는 주로 전망 칭찬.",
      "when": "취향에 따라 기존 카페와 교체",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260920105306_photo1_94bee5dcdc64.webp",
      "source": "https://www.diningcode.com/profile.php?rid=6q4LCiNGnaYs",
      "credit": "다이닝코드 · 낙조대 카페",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "주차장 · 대기 유의",
      "parking": "주차 안내 인력과 입차 대기 후기가 있어요. 주차 최우선 후보로 고르지는 않았어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=6q4LCiNGnaYs"
    },
    {
      "id": "dongyang",
      "name": "동양찻집 영종도본점",
      "type": "cafe",
      "zone": "east",
      "region": "중산·동쪽",
      "kind": "전통차·다과",
      "menu": "쌍화차 / 대추차 / 커피·다과",
      "why": "커피를 이미 마셨거나 차와 다과를 즐기고 싶을 때. 바다 전망 대신 대화와 차를 목적으로 고르는 대안.",
      "caution": "오작로 80. 공개 안내상 월요일 휴무·19:30 마지막 주문. 바다 바로 앞 카페는 아니에요.",
      "review": "네이버 검색 4.92 / 5 · 리뷰 1,750",
      "reviewNote": "검색에 노출된 후기에서 쌍화차·팥빙수·대화하기 좋은 분위기를 언급. 전체 후기의 대표성을 보장하진 않아요.",
      "when": "취향에 따라 기존 카페와 교체",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260628084151_photo1_df3a908da7f3.webp",
      "source": "https://www.diningcode.com/profile.php?rid=hW2RljAH8yG3",
      "credit": "다이닝코드 · 동양찻집 영종도본점",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "전용 주차 안내",
      "parking": "전용 주차 이용 안내가 있으나 규모·실시간 여유는 미확인입니다.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=hW2RljAH8yG3"
    },
    {
      "id": "now",
      "name": "지금이곳",
      "type": "cafe",
      "zone": "central",
      "region": "운남·운북",
      "kind": "정원·베이커리",
      "menu": "베이커리 · 시그니처 라떼 · 케이크",
      "why": "운남동의 잔디·정원과 넓은 공간. 바다 카페를 반복하기보다 빵 고르고 쉬는 시간을 원할 때 추천.",
      "caution": "공개 안내 11~19시. 해변 노을 후 늦은 카페보다 낮 방문에 맞춰요.",
      "review": "다이닝코드 4.2/5 · 32명",
      "reviewNote": "빵 종류·정원·친절함 호평. 음료·빵 가격이 높다는 의견도 있어요.",
      "when": "첫날 입도·마지막 날 카페 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260918033221677_photo_6eee89135ef7.webp",
      "source": "https://www.diningcode.com/profile.php?rid=Xww4aoYeVFHf",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드 기준.",
      "parkingTitle": "주차 우선 후보",
      "parking": "넓은 무료 주차장 후기. 공휴일에는 여유가 달라질 수 있어요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=Xww4aoYeVFHf"
    },
    {
      "id": "bida",
      "name": "비다",
      "type": "cafe",
      "zone": "central",
      "region": "운남·운북",
      "kind": "숲뷰·디저트",
      "menu": "커피 · 바스크 치즈케이크 · 휘낭시에 · 샌드위치",
      "why": "운북동 숲을 마주한 통창 카페. 대형 오션뷰 카페보다 숲·디저트·차분한 실내 취향이면 비교할 곳.",
      "caution": "일부러 이동하는 대안. 지금이곳은 공개 안내 11~19시. 비다는 출처별 영업시간이 달라 방문 전 확인.",
      "review": "다이닝코드 4.8/5 · 13명",
      "reviewNote": "커피·치즈케이크 호평. 평일 여유로웠다는 경험을 주말에 그대로 적용하지 않았어요.",
      "when": "첫날 입도·마지막 날 카페 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260912100835_photo1_db522ba442a2.webp",
      "source": "https://www.diningcode.com/profile.php?rid=ykHPXXfiWdWV",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드 기준.",
      "parkingTitle": "전용 주차 · 진입로 유의",
      "parking": "가게 앞뒤 무료 주차 후기. 좁은 진입로·만차 후기가 있어 주차 최우선 후보는 아닙니다.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=ykHPXXfiWdWV"
    },
    {
      "id": "manjeong",
      "name": "만정수산",
      "type": "food",
      "zone": "east",
      "region": "중산·하늘도시",
      "kind": "왕새우 소금구이",
      "menu": "새우 소금구이 · 머리요리 · 새우튀김 · 해물라면",
      "why": "가을 새우구이가 목적이면 우선 비교할 곳. 해변 카페 중심 일정에서 벗어나 새우 한 끼에 집중하기 좋아요.",
      "caution": "양식 새우 안내가 있어 자연산 대하로 단정하지 않습니다. 당일 어종·가격·주문 마감 확인. 호텔 서쪽과는 별도 이동 필요.",
      "review": "다이닝코드 4.5/5 · 17명",
      "reviewNote": "새우 식감·머리요리 호평과 주말 대기 후기가 함께 있어요.",
      "when": "첫날·마지막 날 식사 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260901085028854_photo_239e0ac70529.webp",
      "source": "https://www.diningcode.com/profile.php?rid=jq0VqiBq3YS5",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드이며 네이버 평점과 다릅니다. 추천 이유는 메뉴와 동선에 따른 편집 판단.",
      "parkingTitle": "주차 우선 후보",
      "parking": "넓은 무료 주차장 후기가 있어 우선 후보. 공휴일 빈자리는 보장되지 않아요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=jq0VqiBq3YS5",
      "naverReview": "네이버 검색 리뷰 1,237 · 별점 미표시",
      "price": "네이버 표시: 새우구이 1kg 50,000원 / 해물라면 12,000원 (10.08 확인, 변동 가능)"
    },
    {
      "id": "cheongchun",
      "name": "청춘조개포차 을왕본점",
      "type": "food",
      "zone": "west",
      "region": "왕산·을왕리",
      "kind": "꽃게구이·조개구이",
      "menu": "꽃게구이 또는 찜 · 활새우구이 · 조개구이",
      "why": "꽃게를 구워 먹고 싶다는 요청에 맞는 후보. 왕산 노을 후 숙소 쪽 저녁으로 비교하기 좋아요.",
      "caution": "꽃게 한정 판매·품절 후기 있음. 방문 전 0507-1363-9760으로 재고·가격 문의 권장.",
      "review": "다이닝코드 4.1/5 · 28명",
      "reviewNote": "가리비·조개 구성 호평. 시끄러움·대기·꽃게 품절 후기도 확인했어요.",
      "when": "해변 노을 뒤 저녁 후보",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260526124412_photo1_6a4c2d126da1.webp",
      "source": "https://www.diningcode.com/profile.php?rid=isOlGzt2j1Az",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드이며 네이버 평점과 다릅니다. 추천 이유는 메뉴와 동선에 따른 편집 판단. 네이버에는 청춘조개 을왕리본점으로 노출되며 주소·전화가 일치합니다. 네이버 별점·리뷰 수는 이 검색 화면에서 미확인.",
      "parkingTitle": "주차 안내 · 혼잡 확인",
      "parking": "무료 주차 후기가 있으나 연휴 주변 주차 대기 사례가 있어요. 식당 지정 주차 위치 확인.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=isOlGzt2j1Az",
      "query": "청춘조개 을왕리본점"
    },
    {
      "id": "seohae",
      "name": "서해수산 본점",
      "type": "food",
      "zone": "east",
      "region": "중산·하늘도시",
      "kind": "왕새우구이",
      "menu": "왕새우구이 · 머리버터구이 · 새우튀김 · 해물라면",
      "why": "만정수산과 함께 비교할 새우 전문 후보. 양식장 곁에서 먹는 분위기를 좋아하면 선택해요.",
      "caution": "가을 주말 대기가 길다는 후기. 당일 새우 종류·재고와 접수 마감을 확인하세요.",
      "review": "다이닝코드 4.7/5 · 24명",
      "reviewNote": "새우·머리버터구이 호평. 대기시간이 일정에 가장 큰 변수예요.",
      "when": "첫날·마지막 날 식사 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260916102252966_photo_dd4b44833aea.webp",
      "source": "https://www.diningcode.com/profile.php?rid=JdbCf7IUmuPy",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드이며 네이버 평점과 다릅니다. 추천 이유는 메뉴와 동선에 따른 편집 판단.",
      "parkingTitle": "주차 안내 · 혼잡 확인",
      "parking": "매장 앞 무료 주차 후기. 넓은 공터도 꽉 찬다는 후기가 있어 편리함을 보장하진 않아요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=JdbCf7IUmuPy",
      "naverReview": "네이버 검색 관련 장소 리뷰 약 1.2만 · 별점 미표시"
    },
    {
      "id": "crab",
      "name": "잇츠크랩",
      "type": "food",
      "zone": "east",
      "region": "중산·하늘도시",
      "kind": "대게·킹크랩",
      "menu": "대게 세트 · 킹크랩(재고 확인) · 볶음밥·라면 구성 확인",
      "why": "게를 편하게 손질해서 먹고 싶을 때의 대안. 구읍뱃터 관광형 식당과 다른 소규모 식사 분위기예요.",
      "caution": "시가·중량·세트 구성 확인. 킹크랩 품절 표기가 있어 당일 전화 확인 필요. 좌석 적어 예약 문의 권장.",
      "review": "다이닝코드 5.0/5 · 2명",
      "reviewNote": "표본이 2명뿐이라 높은 평점을 맛 보장으로 해석하지 않았어요. 손질·분위기 호평.",
      "when": "첫날·마지막 날 식사 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20251003014614_photo1_b24ddcb0bffa.webp",
      "source": "https://www.diningcode.com/profile.php?rid=tTjClpmnzWcg",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드이며 네이버 평점과 다릅니다. 추천 이유는 메뉴와 동선에 따른 편집 판단.",
      "parkingTitle": "주차 안내 · 혼잡 확인",
      "parking": "건물 옆 주차가 협소하다는 후기. 주차 편의 우선이면 순위를 낮추세요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=tTjClpmnzWcg"
    },
    {
      "id": "chusu",
      "name": "추수 솥밥",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 · 오아시스 고메 빌리지",
      "kind": "고메 · 한식 솥밥",
      "menu": "한우 투뿔 솥밥 · 가리비 솥밥 · 숯불 제육 솥밥",
      "why": "점심을 밥 중심으로 든든하게 먹고 오후 구경을 이어갈 때.",
      "caution": "2026.10.03 리뉴얼 기준. 가격·영업시간은 현재 현장 메뉴판 확인. 예전 우물집·온천집 후기를 새 매장 평가로 사용하지 않았어요.",
      "review": "리뉴얼 후 개별 평점 미확인",
      "reviewNote": "이전 푸드코트 통합 평점은 운영 변경 전 후기가 섞여 있어 표시하지 않았습니다.",
      "when": "둘째 날 점심 · 푸드코트 후보",
      "image": "https://image.fnnews.com/resource/media/image/2026/10/03/202610031356381529_e.jpg",
      "source": "https://www.fnnews.com/news/202610031351050945",
      "credit": "인스파이어 제공 · 추수 솥밥 / 파이낸셜뉴스",
      "evidence": "2026.10.01 데일리안·10.03 파이낸셜뉴스 리조트 발표 보도 교차 확인. 5개 직영 브랜드 리뉴얼. 상세 가격 미확인.",
      "info": "https://m.dailian.co.kr/news/view/1696567/",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 리뉴얼 전 할인금액을 현재 정책으로 확정하지 않았어요. 결제할 때 주차 등록·합산 확인.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=lFxU49sTuvtP",
      "query": "인스파이어 고메빌리지 추수 솥밥"
    },
    {
      "id": "jinji",
      "name": "진지",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 · 오아시스 고메 빌리지",
      "kind": "고메 · 한식 국물",
      "menu": "특 한우탕 · 한우 전복 돌미역국 · 돼지고기 김치찌개",
      "why": "늦게 일어나 첫 식사를 따뜻한 국물로 시작하고 싶을 때.",
      "caution": "2026.10.03 리뉴얼 기준. 가격·영업시간은 현재 현장 메뉴판 확인. 예전 우물집·온천집 후기를 새 매장 평가로 사용하지 않았어요.",
      "review": "리뉴얼 후 개별 평점 미확인",
      "reviewNote": "이전 푸드코트 통합 평점은 운영 변경 전 후기가 섞여 있어 표시하지 않았습니다.",
      "when": "둘째 날 점심 · 푸드코트 후보",
      "image": "https://cdnimage.dailian.co.kr/news/202610/news_1790812279385_1696567_m_1.jpg",
      "source": "https://www.fnnews.com/news/202610031351050945",
      "credit": "인스파이어 제공 / 데일리안",
      "evidence": "2026.10.01 데일리안·10.03 파이낸셜뉴스 리조트 발표 보도 교차 확인. 5개 직영 브랜드 리뉴얼. 상세 가격 미확인.",
      "info": "https://m.dailian.co.kr/news/view/1696567/",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 리뉴얼 전 할인금액을 현재 정책으로 확정하지 않았어요. 결제할 때 주차 등록·합산 확인.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=lFxU49sTuvtP",
      "query": "인스파이어 고메빌리지 진지",
      "photoAlt": "오아시스 고메 빌리지 공용 공간 보도 사진",
      "photoSource": "https://m.dailian.co.kr/news/view/1696567/",
      "photoNote": "고메 빌리지 공용 공간 · 해당 브랜드 음식 사진은 미확인"
    },
    {
      "id": "hongmiru",
      "name": "홍미루",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 · 오아시스 고메 빌리지",
      "kind": "고메 · 중식",
      "menu": "오션 짬뽕 · 유니짜장면 · 탕수육",
      "why": "면과 요리를 나눠 먹고 싶을 때. 리조트 홍반과 별개의 매장이에요.",
      "caution": "2026.10.03 리뉴얼 기준. 가격·영업시간은 현재 현장 메뉴판 확인. 예전 우물집·온천집 후기를 새 매장 평가로 사용하지 않았어요.",
      "review": "리뉴얼 후 개별 평점 미확인",
      "reviewNote": "이전 푸드코트 통합 평점은 운영 변경 전 후기가 섞여 있어 표시하지 않았습니다.",
      "when": "둘째 날 점심 · 푸드코트 후보",
      "image": "https://cdnimage.dailian.co.kr/news/202610/news_1790812279385_1696567_m_1.jpg",
      "source": "https://www.fnnews.com/news/202610031351050945",
      "credit": "인스파이어 제공 / 데일리안",
      "evidence": "2026.10.01 데일리안·10.03 파이낸셜뉴스 리조트 발표 보도 교차 확인. 5개 직영 브랜드 리뉴얼. 상세 가격 미확인.",
      "info": "https://m.dailian.co.kr/news/view/1696567/",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 리뉴얼 전 할인금액을 현재 정책으로 확정하지 않았어요. 결제할 때 주차 등록·합산 확인.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=lFxU49sTuvtP",
      "query": "인스파이어 고메빌리지 홍미루",
      "photoAlt": "오아시스 고메 빌리지 공용 공간 보도 사진",
      "photoSource": "https://m.dailian.co.kr/news/view/1696567/",
      "photoNote": "고메 빌리지 공용 공간 · 해당 브랜드 음식 사진은 미확인"
    },
    {
      "id": "tonton",
      "name": "톤톤야",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 · 오아시스 고메 빌리지",
      "kind": "고메 · 일식",
      "menu": "등심 돈카츠 · 치즈 카츠 · 돈코츠 라멘",
      "why": "돈카츠·라멘처럼 익숙한 한 끼가 당길 때.",
      "caution": "2026.10.03 리뉴얼 기준. 가격·영업시간은 현재 현장 메뉴판 확인. 예전 우물집·온천집 후기를 새 매장 평가로 사용하지 않았어요.",
      "review": "리뉴얼 후 개별 평점 미확인",
      "reviewNote": "이전 푸드코트 통합 평점은 운영 변경 전 후기가 섞여 있어 표시하지 않았습니다.",
      "when": "둘째 날 점심 · 푸드코트 후보",
      "image": "https://cdnimage.dailian.co.kr/news/202610/news_1790812279385_1696567_m_1.jpg",
      "source": "https://www.fnnews.com/news/202610031351050945",
      "credit": "인스파이어 제공 / 데일리안",
      "evidence": "2026.10.01 데일리안·10.03 파이낸셜뉴스 리조트 발표 보도 교차 확인. 5개 직영 브랜드 리뉴얼. 상세 가격 미확인.",
      "info": "https://m.dailian.co.kr/news/view/1696567/",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 리뉴얼 전 할인금액을 현재 정책으로 확정하지 않았어요. 결제할 때 주차 등록·합산 확인.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=lFxU49sTuvtP",
      "query": "인스파이어 고메빌리지 톤톤야",
      "photoAlt": "오아시스 고메 빌리지 공용 공간 보도 사진",
      "photoSource": "https://m.dailian.co.kr/news/view/1696567/",
      "photoNote": "고메 빌리지 공용 공간 · 해당 브랜드 음식 사진은 미확인"
    },
    {
      "id": "piazza",
      "name": "피자 피아짜",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 · 오아시스 고메 빌리지",
      "kind": "고메 · 피자",
      "menu": "오션 씨푸드 피자 · 스테이크 피자 · 오븐 치즈 미트 파스타",
      "why": "피자·파스타를 나눠 먹는 점심이 좋을 때.",
      "caution": "2026.10.03 리뉴얼 기준. 가격·영업시간은 현재 현장 메뉴판 확인. 예전 우물집·온천집 후기를 새 매장 평가로 사용하지 않았어요.",
      "review": "리뉴얼 후 개별 평점 미확인",
      "reviewNote": "이전 푸드코트 통합 평점은 운영 변경 전 후기가 섞여 있어 표시하지 않았습니다.",
      "when": "둘째 날 점심 · 푸드코트 후보",
      "image": "https://cdnimage.dailian.co.kr/news/202610/news_1790812279385_1696567_m_1.jpg",
      "source": "https://www.fnnews.com/news/202610031351050945",
      "credit": "인스파이어 제공 / 데일리안",
      "evidence": "2026.10.01 데일리안·10.03 파이낸셜뉴스 리조트 발표 보도 교차 확인. 5개 직영 브랜드 리뉴얼. 상세 가격 미확인.",
      "info": "https://m.dailian.co.kr/news/view/1696567/",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 리뉴얼 전 할인금액을 현재 정책으로 확정하지 않았어요. 결제할 때 주차 등록·합산 확인.",
      "parkingPreferred": true,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=lFxU49sTuvtP",
      "query": "인스파이어 고메빌리지 피자 피아짜",
      "photoAlt": "오아시스 고메 빌리지 공용 공간 보도 사진",
      "photoSource": "https://m.dailian.co.kr/news/view/1696567/",
      "photoNote": "고메 빌리지 공용 공간 · 해당 브랜드 음식 사진은 미확인"
    },
    {
      "id": "hwanghae",
      "type": "food",
      "name": "황해해물칼국수 2호점",
      "region": "마시안·거잠포",
      "kind": "해물칼국수",
      "when": "추천 · 마지막 날 트레킹 후 점심",
      "why": "조개·새우·가리비가 들어가는 따뜻한 국물 한 끼. 무의도에서 나와 마시안 카페로 이어가기 편한 위치예요.",
      "menu": "해물칼국수 / 전복·산낙지 추가",
      "caution": "해물칼국수 13,000원 안내 기준 · 현장 가격 확인. 인기 시간대 대기 가능.",
      "image": "https://media.triple.guide/triple-cms/c_limit%2Cf_auto%2Ch_1024%2Cw_1024/2ed39eaf-ef75-4935-8dde-35c918630c6e.jpeg",
      "source": "https://triple.guide/restaurants/a2a6c288-3807-4671-8c4e-8f9936e98e55",
      "info": "https://www.diningcode.com/profile.php?rid=kvlnOX3rjk1t",
      "credit": "트리플 · 황해해물칼국수",
      "evidence": "마시란로 37. 관광정보·맛집 안내상 09:00~19:00. 연휴 특별영업은 미확인.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "넓은 주차장 안내",
      "parking": "관광정보에 건물 뒤 넓은 무료 주차장 안내. 식사 피크에는 입차 대기가 생길 수 있어요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.ktourmap.com/spotDetails.jsp?contentId=2837152"
    },
    {
      "id": "neulmok",
      "type": "food",
      "name": "늘목쌈밥",
      "region": "용유·숙소 주변 권역",
      "kind": "한식·쌈밥",
      "when": "추천 · 첫날 저녁 / 마지막 날 점심 대안",
      "why": "면이나 해산물 대신 쌈채소·고기·반찬으로 든든하게 먹고 싶을 때. 해변 관광 중심 일정에 한식 한 끼를 넣기 좋아요.",
      "menu": "제육 쌈밥 / 서대구이 등 한상 메뉴",
      "caution": "공개 안내상 브레이크타임·화요일 휴무가 있음. 저녁 방문 전 마지막 주문 확인. 최신 가격 미확인.",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20240901053210807_photo_1b6da2964368.webp",
      "source": "https://www.diningcode.com/profile.php?rid=wJkzPs7HNRk4",
      "credit": "다이닝코드 · 늘목",
      "evidence": "용유서로 158. 메뉴와 위치는 매장·맛집 공개정보 확인. 사진은 과거 방문 사진.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "주차 세부 미확인",
      "parking": "전용 주차장 여부·규모를 확인하지 못해 주차 우선 후보에서는 제외했어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=wJkzPs7HNRk4"
    },
    {
      "id": "donghae",
      "type": "food",
      "name": "동해막국수 영종점",
      "query": "영종도 동해막국수",
      "region": "을왕리·왕산 권역",
      "kind": "막국수·수육",
      "when": "추천 · 서쪽에서 점심 / 이른 저녁 대안",
      "why": "물회보다 익힌 고기와 면이 끌릴 때. 막국수에 메밀전이나 수육을 나눠 먹는 조합으로 취향을 맞추기 좋아요.",
      "menu": "물막국수 / 비빔막국수 / 메밀전 / 수육",
      "caution": "영업·마지막 주문 및 현재 가격은 방문 전 확인.",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20231026012313_photo1_c9e622eb7b69.jpg",
      "source": "https://www.diningcode.com/profile.php?rid=GlwuhNH8gtOB",
      "credit": "다이닝코드 · 동해막국수",
      "evidence": "용유서로479번길 16. 메뉴·주소는 맛집 안내에서 확인. 왕산 관광 공식 페이지에도 주변 식당으로 소개.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "주차 세부 미확인",
      "parking": "전용 주차장 여부·규모를 확인하지 못해 주차 우선 후보에서는 제외했어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=GlwuhNH8gtOB"
    },
    {
      "id": "seonnyeopung",
      "type": "food",
      "name": "선녀풍",
      "query": "영종도 선녀풍 본점",
      "region": "용유·선녀바위 권역",
      "kind": "해산물 물회",
      "when": "추천 · 해산물 좋아하면 점심 후보",
      "why": "차가운 새콤한 국물과 여러 해산물을 즐기고 싶을 때. 따뜻한 칼국수와 성격이 달라 취향에 따라 고르기 좋아요.",
      "menu": "해산물 물회",
      "caution": "익히지 않은 해산물 메뉴. 지점이 있으니 본점·2호점을 구분하세요. 늦은 저녁 방문 전 영업 확인. 가격 미확인.",
      "image": "https://ak-d.tripcdn.com/images/1mi2i2215f752puv434F1.jpg?proc=source%2Ftrip",
      "source": "https://www.trip.com/moments/poi-seonnyeopung-17376101/",
      "credit": "Trip.com · 선녀풍",
      "evidence": "방문자 사진·장소 안내에 기반한 후보. 당일 영업 및 제공 해산물 구성은 미확인.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요.",
      "parkingTitle": "주차 세부 미확인",
      "parking": "전용 주차장 여부·규모를 확인하지 못해 주차 우선 후보에서는 제외했어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.trip.com/moments/poi-seonnyeopung-17376101/"
    },
    {
      "id": "kokmak",
      "name": "바다앞꼬막집",
      "type": "food",
      "zone": "east",
      "region": "구읍뱃터·동쪽",
      "kind": "꼬막비빔밥·한식",
      "menu": "꼬막무침·비빔밥 / 새우전",
      "why": "동쪽에서 밥 한 끼를 고른다면 우선 후보. 꼬막과 새우전을 나눠 먹고 같은 건물의 바다앞테라스로 이어가기 좋아요.",
      "caution": "양념 있는 해산물 밥상. 브레이크타임·주문 인원 조건 확인. 서쪽 호텔로 이동 시간을 남겨두세요.",
      "review": "다이닝코드 4.5 / 5 · 32명",
      "reviewNote": "공개 후기에서 꼬막과 새우전 조합, 바다 전망이 언급됨. 네이버 수치는 별도 미확인.",
      "when": "추천 · 첫날 점심",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260518103359713_photo_2f7b632528dd.webp",
      "source": "https://www.diningcode.com/profile.php?rid=UYFbDHYh7wMA",
      "credit": "다이닝코드 · 바다앞꼬막집",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "건물 지하 · 혼잡 유의",
      "parking": "지하 주차장 이용 후기. 자리가 적다는 후기도 있어요. 공영주차장 대안을 확인하세요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=UYFbDHYh7wMA"
    },
    {
      "id": "miae",
      "name": "미애네회칼국수 왕산점",
      "type": "food",
      "zone": "west",
      "region": "왕산·서쪽",
      "kind": "해물칼국수·조개전골",
      "menu": "바닷속 칼국수 / 짬뽕 칼국수 / 파래전",
      "why": "황해와 비교할 해물칼국수 후보. 왕산 쪽에서 식사하고 싶거나 맑은 국물·매콤한 국물을 고르고 싶을 때.",
      "caution": "공개 안내상 마지막 주문 20:10. 19시 라이딩 종료 후 이동 여유 확인. 지점 구분 필요.",
      "review": "다이닝코드 4.6 / 5 · 9명",
      "reviewNote": "해물 양과 넓은 매장을 칭찬하는 후기. 평가 표본이 작아 높은 별점만으로 우열 판단은 어려움.",
      "when": "첫날·마지막 날 후보",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260531030009_photo1_638cfd8288c3.webp",
      "source": "https://www.diningcode.com/profile.php?rid=Ye6eYk4n9Jjw",
      "credit": "다이닝코드 · 미애네회칼국수 왕산점",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "주차 편리 후기 · 세부 미확인",
      "parking": "주차가 편했다는 후기는 있으나 전용 여부와 규모는 확인되지 않았어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=Ye6eYk4n9Jjw"
    },
    {
      "id": "yang",
      "name": "을왕리양자강 영종도본점",
      "type": "food",
      "zone": "west",
      "region": "왕산·을왕리",
      "kind": "중식·왕갈비짬뽕",
      "menu": "왕갈비짬뽕 / 삼선간짜장 / 탕수육",
      "why": "칼국수 말고 진한 국물이나 짜장면이 끌릴 때. 둘이 짬뽕·간짜장을 나눠 먹는 조합으로 비교해 보세요.",
      "caution": "갈비짬뽕 품절·웨이팅 후기가 있음. 공개 안내상 마지막 주문 20시여서 늦은 저녁은 여유 확인.",
      "review": "네이버 검색 리뷰 약 2.5만 · 별점 미표시",
      "reviewNote": "네이버 검색 노출 후기에서 갈비의 부드러움·양, 간짜장·탕수육 언급. 다이닝코드는 4.1/5·35명.",
      "when": "추천 · 첫날 점심 또는 저녁",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260831023935349_photo_56cf4d5a0abf.webp",
      "source": "https://www.diningcode.com/profile.php?rid=CPKKBkSy27ti",
      "credit": "다이닝코드 · 을왕리양자강 영종도본점",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "매장 앞·옆 주차",
      "parking": "주차 공간 규모에 대한 후기가 엇갈려요. 만차 시 대안을 확인하세요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=CPKKBkSy27ti"
    },
    {
      "id": "jjang",
      "name": "빨간거짱구네 본점",
      "type": "food",
      "zone": "central",
      "region": "운서·중부",
      "kind": "낙지전골",
      "menu": "빨간거 / 하얀거(연포탕) / 볶음밥",
      "why": "면보다 전골을 먹고 싶거나 매콤한 식사를 원하는 날. 낙지전골 뒤 볶음밥으로 마무리하는 든든한 한 끼.",
      "caution": "본점은 햇내로안길 18-7. 서쪽 호텔과는 별도 이동 필요. 공개 메뉴는 빨간거 1인 30,000원으로 예산 확인.",
      "review": "다이닝코드 4.4 / 5 · 12명",
      "reviewNote": "맛 세부 평가가 가격 평가보다 높게 나타남. 맛 위주 후보지만 저렴한 한 끼를 기대하면 덜 맞아요.",
      "when": "맛 우선 · 첫날 점심 / 이동 감수",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20260914124834332_photo_0caf5de8a3e4.webp",
      "source": "https://www.diningcode.com/profile.php?rid=BP53vRQiNsxv",
      "credit": "다이닝코드 · 빨간거짱구네 본점",
      "evidence": "2026-10-08 공개자료 확인. 다이닝코드 평가는 네이버 평점과 별개이며 5점 척도. 리뷰 수는 화면 표기 기준.",
      "instagram": null,
      "parkingTitle": "주차 가능 · 도보 거리 유의",
      "parking": "주차가 매장과 떨어져 불편했다는 후기가 있어요.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=BP53vRQiNsxv"
    },
    {
      "id": "donsadon",
      "name": "돈사돈 영종직영점",
      "type": "food",
      "zone": "east",
      "region": "중산·하늘도시",
      "kind": "제주 흑돼지",
      "menu": "흑돼지 근고기 · 멜젓",
      "why": "해산물을 연속으로 먹고 싶지 않을 때의 고기 대안. 하늘도시에서 식사 후 카페로 이어가기 좋아요.",
      "caution": "고기 중량·최소 주문 확인. 서쪽 숙소로 돌아가려면 추가 이동이 있어요.",
      "review": "다이닝코드 4.0/5 · 1명",
      "reviewNote": "평가 수가 적어 평점보다 메뉴 취향을 기준으로 선택하세요.",
      "when": "첫날·마지막 날 식사 대안",
      "image": "https://d12zq4w4guyljn.cloudfront.net/750_750_20221215051312660_photo_c69bf7b960a4.webp",
      "source": "https://www.diningcode.com/profile.php?rid=oWr74baG0jgr",
      "credit": "다이닝코드 · 매장/이용자 사진",
      "evidence": "2026.10.08 공개 매장정보·노출 후기 확인. 평점은 다이닝코드이며 네이버 평점과 다릅니다. 추천 이유는 메뉴와 동선에 따른 편집 판단.",
      "parkingTitle": "주차 안내 · 혼잡 확인",
      "parking": "건물 지하 주차 지원 후기. 현재 무료 시간·차량 등록은 매장 확인.",
      "parkingPreferred": false,
      "parkingSource": "https://www.diningcode.com/profile.php?rid=oWr74baG0jgr"
    },
    {
      "id": "chef",
      "name": "셰프스 키친",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "인터내셔널 뷔페",
      "menu": "여러 종류의 요리·라이브 키친",
      "why": "둘째 날 점심 자체를 길게 즐기고 싶을 때. 서로 먹고 싶은 메뉴가 달라도 고르기 편한 뷔페.",
      "caution": "공식 주말 점심 12~14시. 예산·예약 가능 여부를 먼저 확인하세요.",
      "review": "네이버 검색 4.76 / 5 · 리뷰 2,868",
      "reviewNote": "노출 후기에서 스테이크·다양한 구성 언급. 브런치·석식 후기도 섞여 토요일 점심 구성과 같다고 볼 수 없음.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_540%2Ch_485%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/1226_Chef_s_Kitchen__4_.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 셰프스 키친",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 셰프스 키친",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "mj",
      "name": "마이클 조던 스테이크 하우스",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "스테이크·기념일 식사",
      "menu": "스테이크 / 해산물 / 코스",
      "why": "고기와 분위기에 예산을 쓰고 싶을 때. 둘째 날 리조트에서 특별한 점심을 계획하는 선택.",
      "caution": "공식 주말·휴일 점심 11:30~14:30. 가격과 예약 확인 필요.",
      "review": "네이버 검색 4.8 / 5 · 리뷰 672",
      "reviewNote": "기념일·분위기·스테이크를 칭찬하는 노출 후기. 디너 후기와 점심 상품은 구분해야 해요.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_540%2Ch_485%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/GMPIK_MJ_Steak_House.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 마이클 조던 스테이크 하우스",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 마이클 조던 스테이크 하우스",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "hong",
      "name": "홍반",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "중식",
      "menu": "중국 요리 / 북경오리 등",
      "why": "중식으로 제대로 한 끼 먹고 싶을 때. 나눠 먹는 요리와 비교적 분리된 좌석 분위기를 선호하면 후보.",
      "caution": "공식 금·토 11~22시. 북경오리 사전 주문·현재 세트 구성은 예약 시 확인.",
      "review": "네이버 검색 리뷰 211 · 별점 미표시",
      "reviewNote": "노출 후기에서 북경오리와 좌석 배치를 칭찬. 최근 모든 후기를 전수 확인한 결과는 아님.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_540%2Ch_485%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/1228_Hong_Pan__3_.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 홍반",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 홍반",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "hifi",
      "name": "하이파이 코리안 소울 푸드",
      "type": "food",
      "zone": "inspire",
      "region": "인스파이어 내부",
      "kind": "캐주얼 한식",
      "menu": "현대적으로 풀어낸 한식·포차 메뉴",
      "why": "둘째 날 점심에 한식이 당길 때. 고급 코스보다 편하게 먹는 방향의 대안.",
      "caution": "공식 점심 12~16시. 구체적인 최신 메뉴·가격은 현장 메뉴 확인.",
      "review": "네이버 평점·리뷰 수 미확인",
      "reviewNote": "공식 메뉴 성격 기반 후보. 맛에 대한 방문자 평가가 확인된 식당과 구분해서 보세요.",
      "when": "둘째 날 · 리조트 안에서 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_540%2Ch_485%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20Hotels%20and%20Resorts/G/GMPIKHI/Hi-Fi%20wall_1.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/",
      "credit": "Hilton 공식 · 하이파이 코리안 소울 푸드",
      "evidence": "2026-10-08 Hilton 공식 다이닝 및 네이버지도 검색 화면 확인. 가격·예약 잔여석은 미확인.",
      "query": "인스파이어 하이파이 코리안 소울 푸드",
      "parkingTitle": "한 번 주차 후 내부 이동",
      "parking": "리조트 공용 주차장. 식사·카페·구경을 한 번 주차로 묶기 좋아요. 비숙박 할인·합산은 결제 매장에서 확인하세요.",
      "parkingPreferred": true,
      "parkingSource": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/dining/"
    },
    {
      "id": "hanagae",
      "type": "walk",
      "name": "하나개 해상관광탐방로",
      "query": "무의도 해상관광탐방로",
      "region": "무의도·하나개",
      "kind": "바다 위 데크 산책",
      "when": "대안 · 마지막 날 소무의도 대신",
      "why": "해안 바위와 바다를 가까이 보며 데크를 걷는 코스. 섬 산길보다 해안 풍경 중심으로 짧게 걷고 싶을 때 골라요.",
      "menu": "데크 약 800m · 해변 포함 1시간 안팎 배정 제안",
      "caution": "하나개해수욕장 쪽 주차 후 해변·데크 산책. 기상·시설 사정에 따른 당일 통제 확인.",
      "image": "https://itour.incheon.go.kr/common/viewImg.do?imgId=API21121010002002302",
      "source": "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=APD21121010002001582",
      "credit": "인천투어 · 해상관광탐방로",
      "evidence": "공식 소개의 초기 550m + 연장 250m를 합산. 1시간은 해변·사진을 포함한 일정 제안이며 공식 소요시간은 아님.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요."
    },
    {
      "id": "wangsan",
      "type": "walk",
      "name": "왕산해수욕장",
      "region": "왕산·서쪽",
      "kind": "모래사장·노을",
      "when": "고정 · 둘째 날 16:30~18:30",
      "why": "모래사장을 걷는 영상과 해를 배경으로 한 실루엣을 담는 시간. 촬영 장소를 자주 옮기지 않고 한 곳에 오래 머물러요.",
      "menu": "백사장 자유 산책 · 30~60분 제안",
      "caution": "일몰 오후 6시 전후 기준. 정확한 일몰·물때·구름은 당일 확인. 연휴 혼잡 가능.",
      "image": "https://itour.incheon.go.kr/common/viewImg.do?imgId=DBI21122413295529552",
      "source": "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21122413280222290",
      "credit": "인천투어 · 왕산해수욕장",
      "evidence": "모래사장·낙조 명소는 공식 소개 확인. 사진의 계절·날씨는 여행일과 다름.",
      "zone": "west",
      "review": "네이버 평점·리뷰 수 직접 확인 안 됨",
      "reviewNote": "기존 후보 · 메뉴·장소 소개 기반. 아래 원문에서 최근 후기를 확인하세요."
    }
  ],
  "days": [
    {
      "title": "자전거 타고, 바다로",
      "date": "10.09 금",
      "sub": "안양 → 체크인 → 자전거",
      "image": "https://itour.incheon.go.kr/common/viewImg.do?imgId=DBI21122413295529552",
      "credit": "인천투어 · 왕산해수욕장",
      "source": "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21122413280222290",
      "highlight": "15시 체크인 · 16:30 외출",
      "description": "15시 체크인 후 쉬고 16:30에 호텔에서 출발해 자전거를 2시간 탄 뒤 저녁을 먹는 희망 일정입니다. 17~19시 이용 가능한 대여처는 아직 확보되지 않았어요.",
      "events": [
        [
          "12:00",
          "안양에서 합류",
          "안양에서 만나 출발 준비"
        ],
        [
          "12:00~12:15 목표",
          "안양에서 영종도로 출발",
          "합류·짐 싣기 후 출발하는 계획"
        ],
        [
          "13:30~14:30 목표",
          "이동 중 또는 영종도에서 점심",
          "교통에 따라 조정 / 15시 체크인을 우선해 대기 짧은 식당 선택"
        ],
        [
          "15:00",
          "제이앤파크호텔 체크인",
          "짐 정리·휴식",
          true
        ],
        [
          "16:30",
          "자전거 타러 호텔 출발 · 조건부",
          "늦은 대여·반납 가능한 업체 확인 필요 / 실제 탑승 시작 시각 아님",
          true
        ],
        [
          "17:00 목표",
          "자전거 2시간 · 조건부",
          "이동·대여 후 17~19시 편성 / 실제 시작은 대여처에 따라 조정",
          true
        ],
        [
          "19:00 이후",
          "자전거 반납 후 저녁",
          "반납·식당 이동 포함 / 식당 마지막 주문 확인"
        ],
        [
          "20:30 전후",
          "호텔 복귀·휴식",
          "저녁 위치에 따라 조정"
        ],
        [
          "20시 전 복귀 시",
          "호텔 수영장 · 선택",
          "일찍 돌아오고 이용 가능할 때만 / 식사·구경을 서두르지 않기"
        ]
      ],
      "note": "씨사이드파크 바다 자전거는 트리플 안내상 13:00~17:00여서 이번 2시간 저녁 라이딩 일정과 맞지 않아요. 19시 이후 반납 가능한 업체·야간 이용 구간·전기자전거 확보가 필요합니다. 첫날 일몰은 18:06 안내로 라이딩 도중 해가 집니다. 별도 해변 영상 촬영은 둘째 날 왕산 일정으로 유지합니다. 수영장: 12층 인피니티풀은 10월 15~21시·투숙객 무료 안내(여기어때). 20시 입장 마감 후기가 있어 호텔 도착 시각과 입장 가능 시각은 다를 수 있어요. 체크인 때 입장 마감·연박 둘째 날 이용 가능 여부를 확인하세요. 수영복·아쿠아슈즈 준비.",
      "rentalSource": "https://triple.guide/attractions/a0602e48-709b-4668-83a3-19147c681b03",
      "poolSource": "https://www.yeogi.com/domestic-accommodations/69725"
    },
    {
      "title": "인스파이어에서 느긋한 하루",
      "date": "10.10 토",
      "sub": "인스파이어 집중 · 왕산 노을은 선택",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_1110%2Ch_886%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Destination%20Photography/Hilton%20International/G/GMPIKHI/0104_Aurora__4_.jpg",
      "credit": "Hilton · 인스파이어 오로라",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/things-to-do/attractions/",
      "highlight": "점심 이후에도 3~4시간 구경",
      "description": "점심 → 오로라·로툰다 → 쇼핑 → 카페 또는 르 스페이스. 리조트에 더 있고 싶으면 저녁까지 이어가요. 해변 노을이 우선이면 16:30 출차를 목표로 선택하세요.",
      "events": [
        [
          "09:30~10:00",
          "기상·준비",
          "아침은 가볍게 / 리조트에서 점심"
        ],
        [
          "10:30~11:00",
          "호텔에서 출발",
          "인스파이어 이동·주차"
        ],
        [
          "11:30~13:00",
          "도착·점심",
          "고메 빌리지 5개 신규 브랜드 또는 리조트 식당"
        ],
        [
          "13:00~14:00",
          "오로라·로툰다·원더",
          "상영 시각은 당일 현장 안내 확인"
        ],
        [
          "14:00~16:30",
          "쇼핑·카페 또는 르 스페이스",
          "전시 관람을 선택하면 1~2시간 확보, 쇼핑은 취향대로 조정"
        ],
        [
          "16:30 선택",
          "A. 왕산 노을 보러 출발",
          "출차·이동·주차 후 17시대 해변 도착 목표. 오후 6시 전후 노을 촬영.",
          true
        ],
        [
          "16:30 이후",
          "B. 리조트에 더 머물기",
          "쇼핑·전시·저녁까지. 이 경우 이날 해변 노을은 생략"
        ],
        [
          "18:30 이후",
          "저녁 식사",
          "A는 왕산·을왕리 / B는 인스파이어 내부"
        ],
        [
          "저녁 후",
          "호텔 복귀",
          "컨디션 좋으면 짧은 해변 밤산책"
        ],
        [
          "20시 전 복귀 시",
          "호텔 수영장 · 선택",
          "일찍 돌아오고 이용 가능할 때만 / 식사·구경을 서두르지 않기"
        ]
      ],
      "note": "노을과 긴 리조트 체류는 선택 관계예요. 왕산으로 갈 경우 16:30 출차 목표, 출차·교통·주차가 밀리면 촬영 시간이 줄어듭니다. 유료 전시 관람과 주차 할인은 별도 확인. 수영장: 12층 인피니티풀은 10월 15~21시·투숙객 무료 안내(여기어때). 20시 입장 마감 후기가 있어 호텔 도착 시각과 입장 가능 시각은 다를 수 있어요. 체크인 때 입장 마감·연박 둘째 날 이용 가능 여부를 확인하세요. 수영복·아쿠아슈즈 준비.",
      "poolSource": "https://www.yeogi.com/domestic-accommodations/69725"
    },
    {
      "title": "짧게 걷고, 여유롭게 귀가",
      "date": "10.11 일",
      "sub": "체크아웃 → 칼국수 → 예단포·카페",
      "image": "https://itour.incheon.go.kr/upload/image/2025/06/16/ae8edc59-feb4-460f-87a0-edfd46f29474.jpg",
      "credit": "인천투어 · 예단포",
      "source": "https://itour.incheon.go.kr/thmtour/thmtour/detail.do?cotId=ITA25061617575280445",
      "highlight": "11시 체크아웃하고 바로 출발",
      "description": "조은전골칼국수 점심을 우선 후보로. 오후 3시 마감 안내라 식사 후 예단포를 40~60분 걷는 순서를 추천해요.",
      "events": [
        [
          "오전",
          "아침 식사·짐 정리",
          "11시 출발에 맞춰 준비"
        ],
        [
          "10:45~11:00",
          "체크아웃 수속",
          "11시까지 체크아웃 완료",
          true
        ],
        [
          "11:00",
          "호텔에서 출발",
          "조은전골칼국수로 이동 · 점심 우선 후보"
        ],
        [
          "12:00 전후",
          "조은전골칼국수 · 점심 후보",
          "칼국수+맛보쌈 11,000원 / 주차·대기 여유 두기"
        ],
        [
          "13:00 전후",
          "예단포 둘레길",
          "사진·휴식 포함 40~60분 / 식당 대기에 따라 시간 조정"
        ],
        [
          "14:00~15:00",
          "카페 · 선택",
          "비다·지금이곳·핌 카페 등 취향에 맞게 선택"
        ],
        [
          "15:00 이후",
          "여유롭게 귀가",
          "컨디션에 따라 카페 생략 가능"
        ]
      ],
      "note": "이동·주차 시간은 추정이며 실제 교통에 따라 조정합니다. 2시간 이상 배정했던 호룡곡산·백운산·소무의도 코스는 제외했습니다. 예단포·백련산·하나개 중 한 곳만 선택하세요."
    }
  ],
  "routes": {
    "points": {
      "hotel": {
        "name": "제이앤파크호텔",
        "lat": 37.4448639,
        "lng": 126.3790562,
        "note": "숙소 · 예약처 지도 좌표"
      },
      "inspire": {
        "name": "인스파이어 리조트",
        "lat": 37.46522,
        "lng": 126.38822,
        "note": "둘째 날 낮 · 내부 식당·카페 선택"
      },
      "wangsan": {
        "name": "왕산해수욕장",
        "lat": 37.4553676,
        "lng": 126.3693441,
        "note": "둘째 날 노을 촬영"
      },
      "eulwang": {
        "name": "을왕리해수욕장",
        "lat": 37.4469238,
        "lng": 126.3723626,
        "note": "저녁·밤산책 권역"
      },
      "somuui": {
        "name": "소무의도",
        "lat": 37.3727949,
        "lng": 126.4431843,
        "note": "섬 대표 위치 · 차량은 광명항 쪽 주차 후 도보 입도"
      },
      "masian": {
        "name": "마시안해변 권역",
        "lat": 37.4276103,
        "lng": 126.4186504,
        "note": "점심·카페 후보 권역 · 개별 매장 위치는 지도 검색"
      },
      "seaside": {
        "name": "씨사이드파크 · 대여 후보",
        "lat": 37.4824222,
        "lng": 126.5671763,
        "note": "17~19시 자전거 대여 미확인 · 확정 경로에서 제외"
      },
      "yedan": {
        "name": "예단포선착장·둘레길 입구",
        "lat": 37.5314534478937,
        "lng": 126.502439167743,
        "note": "인천투어 공식 예단포 지도 좌표 · 무료 주차 안내 · 정자 방향 원점 회귀"
      },
      "joeun": {
        "name": "조은전골칼국수 · 점심 후보",
        "lat": 37.4931801,
        "lng": 126.5429878,
        "note": "운중로 84 · 다이닝코드 지도 좌표 · 일요일 15시 마감 안내 · 방문 미확정"
      }
    },
    "days": [
      {
        "ids": [
          "hotel"
        ],
        "note": "12시 안양 합류 → 영종도 점심 → 15시 체크인. 출발·이동 시각은 계획이며 교통에 따라 조정해요. 안양의 상세 출발 위치는 공개하지 않으며 지도는 영종도부터 표시합니다.",
        "extra": [
          "seaside"
        ]
      },
      {
        "ids": [
          "hotel",
          "inspire"
        ],
        "note": "기본: 호텔 → 인스파이어에서 점심·오후 구경·쇼핑. 선택 A: 16:30 출차 후 왕산 노을·을왕리 저녁. 선택 B: 리조트에서 저녁까지. 주황 핀은 선택 코스, 점선은 도로 경로가 아닙니다.",
        "extra": [
          "wangsan",
          "eulwang"
        ]
      },
      {
        "ids": [
          "hotel",
          "joeun",
          "yedan"
        ],
        "extra": [],
        "note": "추천 선택안: 11시 체크아웃 → 조은전골칼국수 점심 → 예단포 40~60분 → 카페·귀가. 식당은 우선 후보이며 예약·방문 확정이 아닙니다."
      }
    ]
  },
  "shopping": [
    [
      "아크메드라비",
      "캐주얼 의류",
      "옷 구경 우선 후보 · 몰 1층",
      "브랜드 공식 매장 안내 확인",
      "https://acmedelavie.com/board/free/read.html?board_no=2&no=33062"
    ],
    [
      "수피 SUPY",
      "패션 편집숍",
      "여러 스타일을 둘러보고 싶을 때 · 몰 1층",
      "입점 브랜드 PEEP의 매장 안내 확인",
      "https://peep-official.com/product/supy-inspire-mall/414/"
    ],
    [
      "버터샵",
      "캐릭터·생활 소품",
      "작은 선물·귀여운 소품을 고를 때 · 몰 1층",
      "2026.09 매장 채용 공고 확인 · 당일 운영 미확인",
      "https://www.shopma.net/job/shop10_read.asp?class_id=04&id=2427577&pgub=prem"
    ],
    [
      "르 스페이스 샵",
      "전시 굿즈·기념품",
      "전시 후 기념품 구경",
      "공식 FAQ에서 판매 안내 확인",
      "https://lespace.co.kr/ice-planet/"
    ],
    [
      "더 모브 · 럭셔리에디션",
      "명품 편집숍",
      "브랜드별 단독 부티크가 아닌 편집숍",
      "2024 입점 보도만 확인 · 현재 입점 현장 확인",
      "https://tnnews.co.kr/archives/174771"
    ],
    [
      "썬투먼 · 마크엠",
      "패션·잡화",
      "추가 쇼핑 후보",
      "2024 입점 보도만 확인 · 현재 입점 현장 확인",
      "https://tnnews.co.kr/archives/174771"
    ],
    [
      "캐리마켓 · 퍼스트드레스",
      "키즈·패밀리 의류",
      "아이 선물을 볼 때의 추가 후보",
      "2024 입점 보도만 확인 · 현재 입점 현장 확인",
      "https://tnnews.co.kr/archives/174771"
    ]
  ],
  "experiences": [
    {
      "name": "오로라",
      "kind": "LED 거리 · 우선 구경",
      "menu": "2층 · 공식 운영 안내 08:00~24:00",
      "why": "천장까지 이어지는 화면을 보며 걷고 영상 남기기 좋은 첫 순서.",
      "caution": "공식 Hilton은 쇼를 1시간마다로 안내합니다. 과거 정각·30분 고래쇼 후기를 그대로 적용하지 말고 현장 상영표 확인.",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_1110%2Ch_886%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Destination%20Photography/Hilton%20International/G/GMPIKHI/0104_Aurora__4_.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/things-to-do/attractions/",
      "credit": "Hilton · 오로라"
    },
    {
      "name": "로툰다",
      "kind": "키네틱 샹들리에",
      "menu": "2층 · 오로라와 묶어서 구경",
      "why": "움직이는 LED 패널과 원형 홀. 오로라 관람 전후 들르기 좋아요.",
      "caution": "Hilton은 저녁 쇼를 19:30·20:30·21:30으로 안내. 토요일 낮 쇼 시각은 해당 안내에 없어 현장 확인. 예전 매시 15·45분을 확정하지 않았어요.",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_720%2Ch_540%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20International/G/GMPIKHI/GMPIK_Rotunda.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/things-to-do/attractions/",
      "credit": "Hilton · 로툰다"
    },
    {
      "name": "르 스페이스 : ICE PLANET",
      "kind": "유료 미디어아트 · 선택",
      "menu": "몰 1층 · 1~2시간 · 공식 가격 28,000원부터",
      "why": "리조트에서 오래 놀고 싶을 때 가장 시간을 넉넉히 둘 선택지. 빙하·우주 세계를 체험하는 시즌 2 전시.",
      "caution": "공식 10:00~21:00, 입장 마감 19:30. 날짜별 티켓 가격·잔여 확인. 매표소 사전 차량 등록 시 주차 3시간 지원, 다른 할인과 합산 여부는 확인.",
      "image": "https://lespace.co.kr/_astro/Opengraph_lespace_mesucv_znhj1p_ZN2fML.jpeg",
      "source": "https://lespace.co.kr/ice-planet/",
      "credit": "르 스페이스 공식"
    },
    {
      "name": "인스파이어 원더",
      "kind": "몰 곳곳 아트 공간",
      "menu": "쇼핑 사이에 나눠 구경",
      "why": "한 번에 전부 돌기보다 쇼핑하며 마주치는 예술 공간에서 사진을 남겨요.",
      "caution": "관람 소요시간은 취향에 따라 조정. 쇼핑과 묶어 30~60분 정도 계획하는 편집 제안.",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_720%2Ch_540%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20Hotels%20and%20Resorts/G/GMPIKHI/0115%20INSPIRE%20Wonders_SPACE.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/things-to-do/attractions/",
      "credit": "Hilton · 인스파이어 원더"
    },
    {
      "name": "디스커버리 파크",
      "kind": "야외 잔디·산책",
      "menu": "리조트 서쪽 야외 · 날씨 좋을 때",
      "why": "실내를 오래 둘러본 뒤 바람 쐬기 좋은 산책 대안.",
      "caution": "공식 공원 24시간, 글래스하우스 주말·공휴일 11~18시 안내. 행사·날씨에 따른 이용 제한은 현장 확인.",
      "image": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill%2Cw_720%2Ch_540%2Cq_80%2Cf_auto%2Cg_auto/Imagery/Property%20Photography/Hilton%20Hotels%20and%20Resorts/G/GMPIKHI/Discovery%20Park.jpg",
      "source": "https://www.hilton.com/ko/hotels/gmpikhi-inspire-entertainment-resort/things-to-do/attractions/",
      "credit": "Hilton · 디스커버리 파크"
    }
  ]
};
